# Generated by Django 5.1 on 2024-08-28 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmoteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('set_id', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='media/chat')),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('is_preprocessed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('file', 'filename'), name='unique_chatfile')],
            },
        ),
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('emote_id', models.TextField()),
                ('parent_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emoteset')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('username', 'metadata'), name='unique_user')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('emotes', models.JSONField(blank=True, default=dict)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('parent_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
