# Generated by Django 5.1 on 2024-09-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default='Untitled Channel', max_length=255, unique=True),
        ),
    ]
