# Generated by Django 5.1 on 2024-08-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(default='Default', max_length=255),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
