# Generated by Django 5.0.7 on 2024-07-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chatlog_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlog',
            name='filename',
        ),
    ]
