# Generated by Django 5.1 on 2024-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name_lower',
            field=models.CharField(default='untitled channel', max_length=255, unique=True),
        ),
    ]
