# Generated by Django 5.1 on 2024-09-01 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_channel_name_lower'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEmote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('emote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emote')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.message')),
            ],
            options={
                'unique_together': {('message', 'emote')},
            },
        ),
    ]
