# Generated by Django 5.0.7 on 2024-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatlog_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
