# Generated by Django 5.0.7 on 2024-08-01 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatlog_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('metadata', models.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ChatLog',
            new_name='ChatFile',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, null=True)),
                ('chat_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chatfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
