# Generated by Django 5.0.7 on 2024-08-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_rename_chatlog_chatfile_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_text',
            new_name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='sentiment_label',
            field=models.TextField(default='_None_Found', max_length=100),
        ),
    ]
