# Generated by Django 5.0.7 on 2024-08-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_message_text_message_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_log',
            new_name='parent_log',
        ),
    ]
