# Generated by Django 5.0.7 on 2024-08-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_chat_log_message_parent_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
