# Generated by Django 5.1 on 2024-08-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_message_topics_message_topic_message_toxicity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sentiment_label',
        ),
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='message',
            name='toxicity',
        ),
    ]
