# Generated by Django 5.1 on 2024-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_message_sentiment_label_remove_message_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmoteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('set_id', models.TextField()),
                ('counts', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
