# Generated by Django 5.1 on 2024-08-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_emoteset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfile',
            name='file',
            field=models.FileField(unique=True, upload_to='media/chat'),
        ),
        migrations.AlterField(
            model_name='emoteset',
            name='set_id',
            field=models.TextField(unique=True),
        ),
    ]
