services:
  backend:
    build:
      context: ${BACKEND_DIR}
    command: >
        sh -c "python manage.py makemigrations &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ${BACKEND_DIR}:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    container_name: backend
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "2.0"

  celery:
    build:
      context: ${BACKEND_DIR}
    volumes:
      - ${BACKEND_DIR}:/app
    command: celery -A backend worker --loglevel=info
    container_name: celery
    depends_on:
      - redis
      - backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: "4.0"

  redis:
    image: redis:latest
    container_name: redis

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: backenddb
      POSTGRES_USER: maire
      POSTGRES_PASSWORD: maire
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "2.0"

  frontend:
    build:
      context: ${FRONTEND_DIR}
    ports:
      - "3000:3000"
      - "49153:49153"
    container_name: frontend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ${FRONTEND_DIR}:/app

volumes:
  postgres_data:
